### ISSUE TITLE
Traceback (most recent call last):   File "detect_spread.py", line 83, in <module> exchange.get_spread_info(logger=LOGGER)

### ISSUE THREAD

**Issue by simartem** [bradleyboyuyang/Binance-Arbitrage#6]
i did everything as defined, paying attention to the versions of each module but having this error : 

Can you please help ?

`(binance_arb) C:\Users\user2\Downloads\Binance-Arbitrage-master>python detect_spread.py
2024-05-29 18:08:01 detect_spread.py(82):<module> WARNING New round for price detection
Traceback (most recent call last):
  File "detect_spread.py", line 83, in <module>
    exchange.get_spread_info(logger=LOGGER)
  File "detect_spread.py", line 59, in get_spread_info
    df.columns = ['symbol_future', 'symbol_spot',
  File "C:\Users\user2\anaconda3\envs\binance_arb\lib\site-packages\pandas\core\generic.py", line 5588, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\user2\anaconda3\envs\binance_arb\lib\site-packages\pandas\core\generic.py", line 769, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\user2\anaconda3\envs\binance_arb\lib\site-packages\pandas\core\internals\managers.py", line 214, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\user2\anaconda3\envs\binance_arb\lib\site-packages\pandas\core\internals\base.py", line 69, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 8 elements

(binance_arb) C:\Users\user2\Downloads\Binance-Arbitrage-master>python
Python 3.8.19 (default, Mar 20 2024, 19:55:45) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

(binance_arb) C:\Users\user2\Downloads\Binance-Arbitrage-master>`

**Comment by bradleyboyuyang** [comment]
Hi, you should change the hyperparameter in the program. The default program retrieves data for December options (search for 12), which might already expire. You should change to your current available options.
